### PR TITLE
AI For Good: channels, new front-page & categories list

### LINKED ISSUE #133: category URL is wrong
## Current Behavior

Go to `History` tab. 
Go to one of the previously published assets. 
There is a smaller `History` link, it points to; `https://commons.oceanprotocol.com/search?text=History`

Remove URL or update?

### PR DESCRIPTION
**Pull request by jernejpregelj**
PR for https://github.com/oceanprotocol/commons/issues/123

- ~~blocked by https://github.com/oceanprotocol/aquarius/issues/179~~ hacky workaround implemented
- ~~blocked by https://github.com/oceanprotocol/aquarius/issues/180~~ hacky workaround implemented
- closes #133
- addresses #118
- addresses #54

### CODE REVIEW

**Comment by kremalicious** [comment]
hihi, https://github.com/oceanprotocol/commons/tree/feature/aiforgood

**Comment by jernejpregelj** [comment]
> hihi, https://github.com/oceanprotocol/commons/tree/feature/aiforgood

I checked PRs but not branches

**Comment by jernejpregelj** [comment]
Current state with Assets from category and all categories listed on homepage
Screenshot 2019-05-15 at 15 15 02

**Comment by jernejpregelj** [comment]
Current state
Screenshot 2019-05-16 at 11 56 20

**Comment by kremalicious** [comment]
current state:

Screen Shot 2019-05-23 at 16 00 12-fullpage

Screen Shot 2019-05-23 at 16 01 07-fullpage

**Comment by jernejpregelj** [comment]
new text about AI for good:

> AI for Good is an initiative to promote the use of artificial intelligence for taking action on the UN SDGs such as fighting poverty, climate change, improving healthcare, etc. The AI for Good commons channel is aimed at helping scale AI for Good by enabling open datasets to be published and shared and connecting AI problem owners with problem solvers.

**Comment by kremalicious** [comment]
current state with actual live data:

Screen Shot 2019-05-27 at 17 45 38-fullpage

Screen Shot 2019-05-27 at 17 45 57-fullpage

Screen Shot 2019-05-27 at 17 46 13-fullpage

Screen Shot 2019-05-27 at 17 47 00-fullpage

**Review by kremalicious — APPROVED** [review]

**Pull request merged**
